name: chewie
description: A video player for Flutter with Cupertino and Material play controls
version: 0.9.7
homepage: https://github.com/brianegan/chewie
authors:
  - Brian Egan <brian@brianegan.com>
  - Ben Hagen <ben@ottomatic.io>

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"

dependencies:
  open_iconic_flutter: ">=0.3.0 <0.4.0"
  video_player:
    git:
      url: "https://github.com/pharshdev/video_player-0.10.1-3.git"
      ref: "6e2d67e4e805b4206584cbb6659eb67b95d30c44"
  screen: ">=0.0.4 <0.1.0"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
